name: Go Test

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20  # 必要なGoのバージョンを指定

    - name: Install dependencies
      run: go mod tidy

    - name: Run tests
      env:
        MONGO_URI: mock_uri
        TEST_ENV: true
      run: go test -v ./...